use super::types::{Table, Column};

pub fn definitions() -> Vec<Table> {
    vec![
        Table {
            name: "uni_v4_pools",
            columns: vec![
                Column { name: "block_number", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "transaction_hash", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "transaction_index", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "log_index", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "log_address", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "pool_id", sql_type: "VARCHAR", nullable: false, primary_key: true },
                Column { name: "currency0", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "currency1", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "fee", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "tick_spacing", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "hooks", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "sqrt_price_x96", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "tick", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "updated_at", sql_type: "TIMESTAMP WITH TIME ZONE", nullable: false, primary_key: false },
            ],
            indexes: vec![],
        },
        Table {
            name: "uni_v4_swaps",
            columns: vec![
                Column { name: "block_number", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "transaction_hash", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "transaction_index", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "log_index", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "log_address", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "pool_id", sql_type: "VARCHAR", nullable: false, primary_key: true },
                Column { name: "sender", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "amount0", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "amount1", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "sqrt_price_x96", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "liquidity", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "tick", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "fee", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "updated_at", sql_type: "TIMESTAMP WITH TIME ZONE", nullable: false, primary_key: false },
            ],
            indexes: vec![],
        },
        Table {
            name: "uni_v4_modify_liquidity",
            columns: vec![
                Column { name: "block_number", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "transaction_hash", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "transaction_index", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "log_index", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "log_address", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "pool_id", sql_type: "VARCHAR", nullable: false, primary_key: true },
                Column { name: "sender", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "tick_lower", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "tick_upper", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "liquidity_delta", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "salt", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "updated_at", sql_type: "TIMESTAMP WITH TIME ZONE", nullable: false, primary_key: false },
            ],
            indexes: vec![],
        },
        Table {
            name: "uni_v4_donations",
            columns: vec![
                Column { name: "block_number", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "transaction_hash", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "transaction_index", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "log_index", sql_type: "BIGINT", nullable: false, primary_key: false },
                Column { name: "log_address", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "pool_id", sql_type: "VARCHAR", nullable: false, primary_key: true },
                Column { name: "sender", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "amount0", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "amount1", sql_type: "VARCHAR", nullable: false, primary_key: false },
                Column { name: "updated_at", sql_type: "TIMESTAMP WITH TIME ZONE", nullable: false, primary_key: false },
            ],
            indexes: vec![],
        },
    ]
}
