use super::types::{Table, Column};

pub fn definitions() -> Vec<Table> {
    vec![
        Table {
            name: "uni_v4_pools",
            columns: vec![
                Column { name: "chain_id", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "block_number", sql_type: "UInt64", nullable: false, primary_key: true },
                Column { name: "block_timestamp", sql_type: "DateTime64(3, 'UTC')", nullable: false, primary_key: false },
                Column { name: "transaction_hash", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "transaction_index", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "log_index", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "log_address", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "pool_id", sql_type: "FixedString(66)", nullable: false, primary_key: false },
                Column { name: "currency0", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "currency1", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "fee", sql_type: "UInt32", nullable: false, primary_key: false },
                Column { name: "tick_spacing", sql_type: "Int32", nullable: false, primary_key: false },
                Column { name: "hooks", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "initial_sqrt_price_x96", sql_type: "Decimal(38,0)", nullable: false, primary_key: false },
                Column { name: "initial_tick", sql_type: "Int32", nullable: false, primary_key: false },
            ],
            indexes: vec![],
            partition_by: Some("toDate(block_timestamp)"),
        },
        Table {
            name: "uni_v4_swaps",
            columns: vec![
                Column { name: "chain_id", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "block_number", sql_type: "UInt64", nullable: false, primary_key: true },
                Column { name: "block_timestamp", sql_type: "DateTime64(3, 'UTC')", nullable: false, primary_key: false },
                Column { name: "transaction_hash", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "transaction_index", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "log_index", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "log_address", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "event_id", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "pool_id", sql_type: "FixedString(66)", nullable: false, primary_key: false },
                Column { name: "sender", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "amount0", sql_type: "Decimal(38,0)", nullable: false, primary_key: false },
                Column { name: "amount1", sql_type: "Decimal(38,0)", nullable: false, primary_key: false },
                Column { name: "sqrt_price_x96", sql_type: "Decimal(38,0)", nullable: false, primary_key: false },
                Column { name: "liquidity", sql_type: "Decimal(38,0)", nullable: false, primary_key: false },
                Column { name: "tick", sql_type: "Int32", nullable: false, primary_key: false },
                Column { name: "fee", sql_type: "UInt32", nullable: false, primary_key: false },
            ],
            indexes: vec![],
            partition_by: Some("toDate(block_timestamp)"),
        },
        Table {
            name: "uni_v4_modify_liquidity",
            columns: vec![
                Column { name: "chain_id", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "block_number", sql_type: "UInt64", nullable: false, primary_key: true },
                Column { name: "block_timestamp", sql_type: "DateTime64(3, 'UTC')", nullable: false, primary_key: false },
                Column { name: "transaction_hash", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "transaction_index", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "log_index", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "log_address", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "event_id", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "pool_id", sql_type: "FixedString(66)", nullable: false, primary_key: false },
                Column { name: "sender", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "tick_lower", sql_type: "Int32", nullable: false, primary_key: false },
                Column { name: "tick_upper", sql_type: "Int32", nullable: false, primary_key: false },
                Column { name: "liquidity_delta", sql_type: "Decimal(38,0)", nullable: false, primary_key: false },
                Column { name: "salt", sql_type: "FixedString(66)", nullable: false, primary_key: false },
            ],
            indexes: vec![],
            partition_by: Some("toDate(block_timestamp)"),
        },
        Table {
            name: "uni_v4_donations",
            columns: vec![
                Column { name: "chain_id", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "block_number", sql_type: "UInt64", nullable: false, primary_key: true },
                Column { name: "block_timestamp", sql_type: "DateTime64(3, 'UTC')", nullable: false, primary_key: false },
                Column { name: "transaction_hash", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "transaction_index", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "log_index", sql_type: "UInt32", nullable: false, primary_key: true },
                Column { name: "log_address", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "event_id", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "pool_id", sql_type: "FixedString(66)", nullable: false, primary_key: false },
                Column { name: "sender", sql_type: "String", nullable: false, primary_key: false },
                Column { name: "amount0", sql_type: "Decimal(38,0)", nullable: false, primary_key: false },
                Column { name: "amount1", sql_type: "Decimal(38,0)", nullable: false, primary_key: false },
            ],
            indexes: vec![],
            partition_by: Some("toDate(block_timestamp)"),
        },
    ]
}
